version: '3.8'

services:
  test-service:
    build: ./test-service
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
